apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: islands

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - cronjob.yaml

commonLabels:
  app.kubernetes.io/name: islands
  app.kubernetes.io/version: "0.1.0"
  app.kubernetes.io/managed-by: kustomize

images:
  - name: islands
    newTag: latest
